# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainwindow.ui'
##
## Created by: Qt User Interface Compiler version 6.4.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QLineEdit,
    QPushButton, QSizePolicy, QStackedWidget, QVBoxLayout,
    QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1280, 960)
        self.verticalLayout = QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.srvc_chk_page = QWidget()
        self.srvc_chk_page.setObjectName(u"srvc_chk_page")
        self.srvc_chk_page.setStyleSheet(u"background: #FFF3C8;")
        self.srvc_chk_frame = QFrame(self.srvc_chk_page)
        self.srvc_chk_frame.setObjectName(u"srvc_chk_frame")
        self.srvc_chk_frame.setGeometry(QRect(64, 48, 1152, 864))
        self.srvc_chk_frame.setAcceptDrops(False)
        self.srvc_chk_frame.setStyleSheet(u"background: #FFFFFF;\n"
"border-radius: 80px;")
        self.srvc_chk_frame.setFrameShape(QFrame.StyledPanel)
        self.srvc_chk_frame.setFrameShadow(QFrame.Raised)
        self.srvc_chk_frame.setLineWidth(20)
        self.srvc_chk_frame.setMidLineWidth(10)
        self.srvc_chk_button = QPushButton(self.srvc_chk_frame)
        self.srvc_chk_button.setObjectName(u"srvc_chk_button")
        self.srvc_chk_button.setGeometry(QRect(522, 620, 108, 108))
        self.srvc_chk_button.setStyleSheet(u"border-radius: 50px;")
        self.srvc_chk_label = QLabel(self.srvc_chk_frame)
        self.srvc_chk_label.setObjectName(u"srvc_chk_label")
        self.srvc_chk_label.setGeometry(QRect(391, 190, 370, 80))
        font = QFont()
        font.setPointSize(36)
        self.srvc_chk_label.setFont(font)
        self.srvc_chk_lineEdit = QLineEdit(self.srvc_chk_frame)
        self.srvc_chk_lineEdit.setObjectName(u"srvc_chk_lineEdit")
        self.srvc_chk_lineEdit.setGeometry(QRect(201, 362, 750, 140))
        self.srvc_chk_lineEdit.setFont(font)
        self.srvc_chk_lineEdit.setStyleSheet(u"background:#D9D9D9;\n"
"border-radius: 40px;")
        self.srvc_chk_lineEdit.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.srvc_chk_page)
        self.home_page = QWidget()
        self.home_page.setObjectName(u"home_page")
        self.home_page.setStyleSheet(u"background:#FFEEEE;")
        self.home_frame = QFrame(self.home_page)
        self.home_frame.setObjectName(u"home_frame")
        self.home_frame.setGeometry(QRect(64, 48, 1152, 864))
        self.home_frame.setStyleSheet(u"background:white;border-radius:100px;")
        self.home_frame.setFrameShape(QFrame.StyledPanel)
        self.home_frame.setFrameShadow(QFrame.Raised)
        self.home_next_button = QPushButton(self.home_frame)
        self.home_next_button.setObjectName(u"home_next_button")
        self.home_next_button.setGeometry(QRect(396, 630, 360, 120))
        font1 = QFont()
        font1.setPointSize(48)
        font1.setBold(True)
        self.home_next_button.setFont(font1)
        self.home_next_button.setStyleSheet(u"background: #FFAB7C;color: white;border-radius:50px;")
        self.home_background = QLabel(self.home_frame)
        self.home_background.setObjectName(u"home_background")
        self.home_background.setGeometry(QRect(58, 80, 1036, 411))
        font2 = QFont()
        font2.setPointSize(60)
        self.home_background.setFont(font2)
        self.home_background.setStyleSheet(u"")
        self.home_background.setScaledContents(True)
        self.home_background.setAlignment(Qt.AlignCenter)
        self.home_text1 = QLabel(self.home_frame)
        self.home_text1.setObjectName(u"home_text1")
        self.home_text1.setGeometry(QRect(330, 350, 481, 91))
        font3 = QFont()
        font3.setPointSize(40)
        self.home_text1.setFont(font3)
        self.home_text1.setAlignment(Qt.AlignCenter)
        self.label_2 = QLabel(self.home_frame)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 470, 901, 61))
        font4 = QFont()
        font4.setPointSize(24)
        self.label_2.setFont(font4)
        self.stackedWidget.addWidget(self.home_page)
        self.info_page = QWidget()
        self.info_page.setObjectName(u"info_page")
        self.info_label = QLabel(self.info_page)
        self.info_label.setObjectName(u"info_label")
        self.info_label.setGeometry(QRect(280, 190, 50, 16))
        self.info_home_button = QPushButton(self.info_page)
        self.info_home_button.setObjectName(u"info_home_button")
        self.info_home_button.setGeometry(QRect(490, 330, 75, 24))
        self.info_next_button = QPushButton(self.info_page)
        self.info_next_button.setObjectName(u"info_next_button")
        self.info_next_button.setGeometry(QRect(480, 390, 75, 24))
        self.info_prev_button = QPushButton(self.info_page)
        self.info_prev_button.setObjectName(u"info_prev_button")
        self.info_prev_button.setGeometry(QRect(360, 390, 75, 24))
        self.stackedWidget.addWidget(self.info_page)
        self.input_page = QWidget()
        self.input_page.setObjectName(u"input_page")
        self.input_next_button = QPushButton(self.input_page)
        self.input_next_button.setObjectName(u"input_next_button")
        self.input_next_button.setGeometry(QRect(460, 400, 75, 24))
        self.input_home_button = QPushButton(self.input_page)
        self.input_home_button.setObjectName(u"input_home_button")
        self.input_home_button.setGeometry(QRect(490, 320, 75, 24))
        self.input_label = QLabel(self.input_page)
        self.input_label.setObjectName(u"input_label")
        self.input_label.setGeometry(QRect(250, 190, 50, 16))
        self.input_prev_button = QPushButton(self.input_page)
        self.input_prev_button.setObjectName(u"input_prev_button")
        self.input_prev_button.setGeometry(QRect(340, 400, 75, 24))
        self.stackedWidget.addWidget(self.input_page)
        self.mode_select_page = QWidget()
        self.mode_select_page.setObjectName(u"mode_select_page")
        self.mode_select_home_button = QPushButton(self.mode_select_page)
        self.mode_select_home_button.setObjectName(u"mode_select_home_button")
        self.mode_select_home_button.setGeometry(QRect(480, 260, 75, 24))
        self.mode_select_image_button = QPushButton(self.mode_select_page)
        self.mode_select_image_button.setObjectName(u"mode_select_image_button")
        self.mode_select_image_button.setGeometry(QRect(170, 380, 75, 24))
        self.mode_select_label = QLabel(self.mode_select_page)
        self.mode_select_label.setObjectName(u"mode_select_label")
        self.mode_select_label.setGeometry(QRect(260, 180, 101, 31))
        self.mode_select_video_button = QPushButton(self.mode_select_page)
        self.mode_select_video_button.setObjectName(u"mode_select_video_button")
        self.mode_select_video_button.setGeometry(QRect(370, 380, 75, 24))
        self.mode_select_prev_button = QPushButton(self.mode_select_page)
        self.mode_select_prev_button.setObjectName(u"mode_select_prev_button")
        self.mode_select_prev_button.setGeometry(QRect(480, 310, 75, 24))
        self.stackedWidget.addWidget(self.mode_select_page)
        self.image_page = QWidget()
        self.image_page.setObjectName(u"image_page")
        self.image_next_button = QPushButton(self.image_page)
        self.image_next_button.setObjectName(u"image_next_button")
        self.image_next_button.setGeometry(QRect(440, 360, 75, 24))
        self.image_home_button = QPushButton(self.image_page)
        self.image_home_button.setObjectName(u"image_home_button")
        self.image_home_button.setGeometry(QRect(470, 300, 75, 24))
        self.image_label = QLabel(self.image_page)
        self.image_label.setObjectName(u"image_label")
        self.image_label.setGeometry(QRect(230, 140, 50, 16))
        self.image_prev_button = QPushButton(self.image_page)
        self.image_prev_button.setObjectName(u"image_prev_button")
        self.image_prev_button.setGeometry(QRect(330, 360, 75, 24))
        self.stackedWidget.addWidget(self.image_page)
        self.video_page = QWidget()
        self.video_page.setObjectName(u"video_page")
        self.video_home_button = QPushButton(self.video_page)
        self.video_home_button.setObjectName(u"video_home_button")
        self.video_home_button.setGeometry(QRect(490, 250, 75, 24))
        self.video_next_button = QPushButton(self.video_page)
        self.video_next_button.setObjectName(u"video_next_button")
        self.video_next_button.setGeometry(QRect(450, 410, 75, 24))
        self.video_label = QLabel(self.video_page)
        self.video_label.setObjectName(u"video_label")
        self.video_label.setGeometry(QRect(290, 160, 50, 16))
        self.video_prev_button = QPushButton(self.video_page)
        self.video_prev_button.setObjectName(u"video_prev_button")
        self.video_prev_button.setGeometry(QRect(500, 300, 75, 24))
        self.stackedWidget.addWidget(self.video_page)
        self.end_page = QWidget()
        self.end_page.setObjectName(u"end_page")
        self.end_home_button = QPushButton(self.end_page)
        self.end_home_button.setObjectName(u"end_home_button")
        self.end_home_button.setGeometry(QRect(470, 370, 75, 24))
        self.end_label = QLabel(self.end_page)
        self.end_label.setObjectName(u"end_label")
        self.end_label.setGeometry(QRect(260, 160, 131, 31))
        self.stackedWidget.addWidget(self.end_page)

        self.verticalLayout.addWidget(self.stackedWidget)


        self.retranslateUi(Form)
        self.home_next_button.clicked.connect(Form.go_next_page)
        self.info_home_button.clicked.connect(Form.go_home_page)
        self.end_home_button.clicked.connect(Form.go_home_page)
        self.image_next_button.clicked.connect(Form.go_end_page)
        self.image_home_button.clicked.connect(Form.go_home_page)
        self.info_next_button.clicked.connect(Form.go_next_page)
        self.input_next_button.clicked.connect(Form.go_next_page)
        self.input_home_button.clicked.connect(Form.go_home_page)
        self.mode_select_image_button.clicked.connect(Form.go_next_page)
        self.mode_select_home_button.clicked.connect(Form.go_home_page)
        self.video_home_button.clicked.connect(Form.go_home_page)
        self.video_next_button.clicked.connect(Form.go_end_page)
        self.mode_select_video_button.clicked.connect(Form.go_next_page)
        self.mode_select_prev_button.clicked.connect(Form.go_prev_page)
        self.video_prev_button.clicked.connect(Form.go_prev_page)
        self.input_prev_button.clicked.connect(Form.go_prev_page)
        self.info_prev_button.clicked.connect(Form.go_prev_page)
        self.image_prev_button.clicked.connect(Form.go_prev_page)
        self.srvc_chk_button.clicked.connect(Form.check_service_validation)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.srvc_chk_button.setText("")
        self.srvc_chk_label.setText(QCoreApplication.translate("Form", u"\uc11c\ube44\uc2a4 \ucf54\ub4dc \uc785\ub825", None))
        self.srvc_chk_lineEdit.setText("")
        self.home_next_button.setText(QCoreApplication.translate("Form", u"\uc2dc\uc791\ud558\uae30", None))
        self.home_background.setText(QCoreApplication.translate("Form", u"Welcome", None))
        self.home_text1.setText(QCoreApplication.translate("Form", u"To the Wedding101", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"\uc2e0\ud63c\ubd80\ubd80 OOO, OOO \ub2d8\uc5d0\uac8c \uc0ac\uc9c4\uc774\ub098 \uc601\uc0c1 \ud3b8\uc9c0\ub97c \ub0a8\uaca8\ubcf4\uc138\uc694", None))
        self.info_label.setText(QCoreApplication.translate("Form", u"Info", None))
        self.info_home_button.setText(QCoreApplication.translate("Form", u"Home", None))
        self.info_next_button.setText(QCoreApplication.translate("Form", u"Next", None))
        self.info_prev_button.setText(QCoreApplication.translate("Form", u"Prev", None))
        self.input_next_button.setText(QCoreApplication.translate("Form", u"Next", None))
        self.input_home_button.setText(QCoreApplication.translate("Form", u"Home", None))
        self.input_label.setText(QCoreApplication.translate("Form", u"Input", None))
        self.input_prev_button.setText(QCoreApplication.translate("Form", u"Prev", None))
        self.mode_select_home_button.setText(QCoreApplication.translate("Form", u"Home", None))
        self.mode_select_image_button.setText(QCoreApplication.translate("Form", u"Image", None))
        self.mode_select_label.setText(QCoreApplication.translate("Form", u"mode select", None))
        self.mode_select_video_button.setText(QCoreApplication.translate("Form", u"Video", None))
        self.mode_select_prev_button.setText(QCoreApplication.translate("Form", u"Prev", None))
        self.image_next_button.setText(QCoreApplication.translate("Form", u"Next", None))
        self.image_home_button.setText(QCoreApplication.translate("Form", u"Home", None))
        self.image_label.setText(QCoreApplication.translate("Form", u"image", None))
        self.image_prev_button.setText(QCoreApplication.translate("Form", u"Prev", None))
        self.video_home_button.setText(QCoreApplication.translate("Form", u"Home", None))
        self.video_next_button.setText(QCoreApplication.translate("Form", u"Next", None))
        self.video_label.setText(QCoreApplication.translate("Form", u"video", None))
        self.video_prev_button.setText(QCoreApplication.translate("Form", u"Prev", None))
        self.end_home_button.setText(QCoreApplication.translate("Form", u"Home", None))
        self.end_label.setText(QCoreApplication.translate("Form", u"Thank you", None))
    # retranslateUi

