FROM nginx:latest

# COPY ./.conf /usr/share/nginx/
COPY ./build /usr/share/nginx/html
# RUN ["mv","/usr/share/nginx/default.conf","/etc/nginx/nginx.conf"]
# RUN ["mv","/usr/share/nginx/myApp.conf","/etc/nginx/conf.d"]
