# Spring boot server port set
server:
  port: 8080

# Spring security Oauth2 client registration
#spring.security.oauth2.client.registration.naver.client-id=<client id>
#spring.security.oauth2.client.registration.naver.client-secret=<client secret>
#spring.security.oauth2.client.registration.naver.redirect-uri={baseUrl}/{action}/oauth2/code/{registrationId}
#spring.security.oauth2.client.registration.naver.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.naver.scope=nickname,email,gender,age,profile_image
#spring.security.oauth2.client.registration.naver.client-name=Naver

# Provider - Naver
#spring.security.oauth2.client.provider.naver.authorization-uri=https://nid.naver.com/oauth2.0/authorize
#spring.security.oauth2.client.provider.naver.token-uri=https://nid.naver.com/oauth2.0/token
#spring.security.oauth2.client.provider.naver.user-info-uri=https://openapi.naver.com/v1/nid/me
#spring.security.oauth2.client.provider.naver.user-name-attribute=response

# Provider - Google
#spring.security.oauth2.client.provider.google.authorization-uri=
#spring.security.oauth2.client.provider.google.token-uri=
#spring.security.oauth2.client.provider.google.user-info-uri=
#spring.security.oauth2.client.provider.google.user-name-attribute=

# Provider - Kakao
#spring.security.oauth2.client.provider.kakao.authorization-uri=
#spring.security.oauth2.client.provider.kakao.token-uri=
#spring.security.oauth2.client.provider.kakao.user-info-uri=
#spring.security.oauth2.client.provider.kakao.user-name-attribute=

spring:
  # ?????? ?? - MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/wedding101_db?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ssafy

  profiles:
    include: db

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  # JPA ??
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      fail-on-empty-beans: false

#spring.jpa.show-sql=true

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    groups-order: desc
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true

  api-docs:
    path: /api-docs

  show-actuator:  true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match: /**
